### ISSUE TITLE
Issue with case statement

### ISSUE THREAD

**Issue by dickvand** [kobbled/tp_plus#22]
Hi Matt, 
I've got some issues with the case statement. It seems that the 'else' statement is mandatory, since it throws an error there is no else case. 
```
    case SubProgram
    when 1
        # case 1
    when 2
        # case 2
    end
```
Error:
```
Traceback (most recent call last):
        7: from C:/Users/d.vandodeweerd/tp_plus/bin/tpp:66:in `<main>'
        6: from C:/Users/d.vandodeweerd/tp_plus/lib/tp_plus/interpreter.rb:121:in `list_warnings'
        5: from C:/Users/d.vandodeweerd/tp_plus/lib/tp_plus/interpreter.rb:89:in `find_warnings'
        4: from C:/Users/d.vandodeweerd/tp_plus/lib/tp_plus/interpreter.rb:89:in `each'
        3: from C:/Users/d.vandodeweerd/tp_plus/lib/tp_plus/interpreter.rb:93:in `block in find_warnings'
        2: from C:/Users/d.vandodeweerd/tp_plus/lib/tp_plus/interpreter.rb:103:in `find_warnings'
        1: from C:/Users/d.vandodeweerd/tp_plus/lib/tp_plus/interpreter.rb:103:in `each'
C:/Users/d.vandodeweerd/tp_plus/lib/tp_plus/interpreter.rb:104:in `block in find_warnings': undefined method `get_block' for nil:NilClass (NoMethodError)
```

Second issue: when I use the case statement inside a function, I get an error too:
```
def test()
    case SubProgram
    when 1
        # case 1
    when 2
        # case 2
    else
        # else
    end
end
```
Error:
```
Traceback (most recent call last):
        12: from C:/Users/d.vandodeweerd/tp_plus/bin/tpp:103:in `<main>'
        11: from C:/Users/d.vandodeweerd/tp_plus/lib/tp_plus/interpreter.rb:135:in `output_functions'
        10: from C:/Users/d.vandodeweerd/tp_plus/lib/tp_plus/interpreter.rb:135:in `each'
         9: from C:/Users/d.vandodeweerd/tp_plus/lib/tp_plus/interpreter.rb:136:in `block in output_functions'        
         8: from C:/Users/d.vandodeweerd/tp_plus/lib/tp_plus/function.rb:77:in `output_program'
         7: from C:/Users/d.vandodeweerd/tp_plus/lib/tp_plus/interpreter.rb:200:in `eval'
         6: from C:/Users/d.vandodeweerd/tp_plus/lib/tp_plus/interpreter.rb:200:in `each'
         5: from C:/Users/d.vandodeweerd/tp_plus/lib/tp_plus/interpreter.rb:204:in `block in eval'
         4: from C:/Users/d.vandodeweerd/tp_plus/lib/tp_plus/nodes/case_node.rb:79:in `eval'
         3: from C:/Users/d.vandodeweerd/tp_plus/lib/tp_plus/nodes/case_node.rb:26:in `first_cond_statement'
         2: from C:/Users/d.vandodeweerd/tp_plus/lib/tp_plus/nodes/case_condition_node.rb:39:in `eval'
         1: from C:/Users/d.vandodeweerd/tp_plus/lib/tp_plus/nodes/case_condition_node.rb:26:in `is_jump_label'       
C:/Users/d.vandodeweerd/tp_plus/lib/tp_plus/nodes/jump_node.rb:17:in `eval': Label (caselbl1) not found (RuntimeError)
        6: from C:/Users/d.vandodeweerd/tp_plus/bin/tpp:103:in `<main>'
        5: from C:/Users/d.vandodeweerd/tp_plus/lib/tp_plus/interpreter.rb:135:in `output_functions'
        4: from C:/Users/d.vandodeweerd/tp_plus/lib/tp_plus/interpreter.rb:135:in `each'
        3: from C:/Users/d.vandodeweerd/tp_plus/lib/tp_plus/interpreter.rb:136:in `block in output_functions'
        2: from C:/Users/d.vandodeweerd/tp_plus/lib/tp_plus/function.rb:77:in `output_program'
        1: from C:/Users/d.vandodeweerd/tp_plus/lib/tp_plus/interpreter.rb:192:in `eval'
C:/Users/d.vandodeweerd/tp_plus/lib/tp_plus/interpreter.rb:219:in `rescue in eval': Runtime error on line 1: (RuntimeError)
```
These issues are not very urgent, because I can work around them, it is just to let you know.

Kind regards,
Dick

**Comment by kobbled** [comment]
626d687 should fix the else statement hopefully. 

Case statements in functions will take me longer to figure out. Just traversing the full node tree recursively is proving a challenge. You would think that would be easy but I cant figure it out. For some reason I cant see if a node has child nodes without explicitly stating the class type while traversing the map. Because everything is its own type you have to explicitly know if its a if, while, for, case statement to know to search into that node for more labels. A work around could be to give those specific types a polymorphic parent class that knows to look into them when you are gathering labels. I believe there are other issues with labels with heavily nested loops because of this.

If you handle the blocks yourself outside of the case statement you can actually get it to compile:
```
def test()
  case SubProgram
  when 1
      jump_to @case1
  when 2
      jump_to @case2
  else
    jump_to @else_block
  end
  
  jump_to @jump
  @case1
    #case 1
  @case2
    #case 2
  @else_block
    #else block
  @jump
end
```

**Comment by kobbled** [comment]
I found another bug addressed in commit a344af0 that would affect case blocks without an else statement.

**Comment by dickvand** [comment]
The issue with the case block without else statement is solved. The workaround for the case inside a function works fine for me.
Thanks!

**Comment by kobbled** [comment]
Hey Dick,

I actually managed to fix the issue with case statements in functions in e36ada9. It was due to a scoping issue, and me incorrectly assigning labels during parsing not evaluation, so the functions couldn't see the labels created. I have a bunch of other calls to `@interpreter` in the parser file that I'm worried about now, but all the unit tests pass, so hopefully everything is ok. I'm not going to reopen the issue for now, but if you notice any problems with labels it might be tangential to this issue.

Best Regards,

Matt
